#!/usr/bin/env bash

programm=$( { tac ~/.dmenu_run_history; dmenu_path; }  | sort | uniq -c | sort -r | awk '{$1=$1};1' | cut -d' ' -f2-  | dmenu -l 44)

if [ 1 -eq $? ]
then
  exit 1
fi

echo "$programm" >> ~/.dmenu_run_history

programm_with_quoted_args="$(printf "%q" "$programm")"

$(${programm_with_quoted_args})


