#!/usr/bin/env bash

source ~/.mpd_current

chosen=$(mpc playlist | nl -s' ' -nln | rofi -dmenu -p "Play now" -i)

# Nothing was selected results in a exit status of 1
if [ 1 -eq $? ]
then
  exit 1
fi

echo ${chosen}

mpc play $(echo ${chosen} | awk "{print \$1}")
