#!/bin/bash

for i in $* 
do
    if [ ! -e $i ]
    then
	echo "Error: File or directory '$PWD/$i' does not exist!";
    else
	dn=$(dirname "$i")
	mkdir -p "~/.trash/$PWD/$dn"
	mv "$i" "~/.trash/$PWD/$i"
    fi
done;



